<a href="https://colab.research.google.com/github/sohyeon1202/ai_python/blob/main/240510.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = [[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']]
df = pd.DataFrame(data, columns=['ID', 'Name'])
df

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [ ]:
url ='https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv'


df4=pd.read_csv(url,delimiter='\t')
df4

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,10,2,0,4,0,55,-1,90,238,157
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,11,7,4,4,1,157,55,119,154,105
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,10,2,0,2,0,113,122,53,11,157
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,11,3,0,1,0,154,39,51,90,114
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,1,0,0,1,0,11,157,141,31,18

In [ ]:
df = pd.read_excel('BoxOffice.xlsx', index_col=0)
df

,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
순위,,,,,,,,,
1,명량,2014-07-30,135758208810,17615844,1587,188724,한국,한국,(주)씨제이이엔엠
2,극한직업,2019-01-23,139655543516,16266338,2003,292816,한국,한국,(주)씨제이이엔엠
3,신과함께-죄와 벌,2017-12-20,115727528087,14414658,1912,214631,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
4,국제시장,2014-12-17,110945002730,14264059,1044,212698,한국,한국,(주)씨제이이엔엠
5,어벤져스: 엔드게임,2019-04-24,122492181020,13977602,2835,246433,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
...,...,...,...,...,...,...,...,...,...
196,스파이,2013-09-05,24513098305,3436092,785,72805,한국,"한국,태국",(주)씨제이이엔엠
197,그것만이 내 세상,2018-01-17,27457704382,3420287,956,95444,한국,한국,(주)씨제이이엔엠
198,토이 스토리 4,2019-06-20,28763352540,3400623,1336,85913,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
199,돈,2019-03-20,28870244062,3389125,1431,120809,한국,한국,(주)쇼박스
200,맨 인 블랙 3,2012-05-24,27301520070,3379762,770,69538,미국,미국,한국소니픽쳐스릴리징브에나비스타영화㈜

In [ ]:
df = pd.read_excel('data.xlsx')
df반이름 = df[['반', '이름']]
print(df반이름)

    반   이름
0  A반  구이서
1  B반  김이정
2  A반  오지수
3  B반  김선후
4  A반  하진희
5  A반  강현진
6  B반  김진솔
7  B반  박서준
8  A반  김성희
9  B반  이지서

In [ ]:
df = pd.read_excel('data.xlsx')
condition_result = df['국어'] >= 80
print(condition_result)
df.sort_values(by=['국어'], ascending=False)

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9     True
Name: 국어, dtype: bool

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
2  A반  오지수  남   NaN    NaN   응시   확인
5  A반  강현진  남   NaN    NaN  NaN  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인

결측치가 있다
1. 아예 제외해버림
2. 채워넣음

결측치 -> 값이 왜곡될 수 있음

In [ ]:
df = pd.read_excel('data.xlsx')
condition_result = df[df['국어'] >= 80]
a = condition_result['국어']
print(a)

0    90.0
6    90.0
9    86.0
Name: 국어, dtype: float64

In [ ]:
df= pd.DataFrame({'학생':['John','Alice','Bob', 'Emily'],
'수학':[90,87,78,92],
'영어':[85,91,80,88],
'과학':[88,89,85,82]})
print(df)

print(df.describe())

a = df['수학'].max()
print(a)
df[df['수학'] == df['수학'.max()]]

b = df[df['수학']>= 90]
print(b)

      학생  수학  영어  과학
0   John  90  85  88
1  Alice  87  91  89
2    Bob  78  80  85
3  Emily  92  88  82
              수학         영어         과학
count   4.000000   4.000000   4.000000
mean   86.750000  86.000000  86.000000
std     6.184658   4.690416   3.162278
min    78.000000  80.000000  82.000000
25%    84.750000  83.750000  84.250000
50%    88.500000  86.500000  86.500000
75%    90.500000  88.750000  88.250000
max    92.000000  91.000000  89.000000
92

AttributeError: 'str' object has no attribute 'max'

In [ ]:
df = pd.read_excel('BoxOffice.xlsx', index_col=0)
df.info()
df.sort_values(by=['대표국적'], ascending=False)
value_counts = df['대표국적'].value_counts()
print(value_counts)

f = df.groupby('대표국적')
b = f.get_group('영국')
print(b)

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화명     200 non-null    object
 1   개봉일     200 non-null    datetime64[ns]
 2   매출액     200 non-null    int64
 3   관객수     200 non-null    int64
 4   스크린수    200 non-null    int64
 5   상영횟수    200 non-null    int64
 6   대표국적    200 non-null    object
 7   국적      200 non-null    object
 8   배급사     200 non-null    object
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 15.6+ KB
대표국적
한국    116
미국     82
일본      1
영국      1
Name: count, dtype: int64
        영화명        개봉일          매출액      관객수  스크린수   상영횟수 대표국적  국적  \
순위
195  어바웃 타임 2013-12-05  25312684300  3449451   568  67267   영국  영국

                     배급사
순위
195  유니버설픽쳐스인터내셔널 코리아(유)